import type { TeamEntry } from './types';

/** National teams (World Cup theme). `iso` is the flagcdn key. */
export const TEAMS: TeamEntry[] = [
  { name: 'Argentina', code: 'ARG', iso: 'ar' },
  { name: 'Brazil', code: 'BRA', iso: 'br' },
  { name: 'France', code: 'FRA', iso: 'fr' },
  { name: 'England', code: 'ENG', iso: 'gb-eng' },
  { name: 'Spain', code: 'ESP', iso: 'es' },
  { name: 'Germany', code: 'GER', iso: 'de' },
  { name: 'Portugal', code: 'POR', iso: 'pt' },
  { name: 'Netherlands', code: 'NED', iso: 'nl', aliases: ['Holland'] },
  { name: 'Italy', code: 'ITA', iso: 'it' },
  { name: 'Belgium', code: 'BEL', iso: 'be' },
  { name: 'Croatia', code: 'CRO', iso: 'hr' },
  { name: 'Uruguay', code: 'URU', iso: 'uy' },
  { name: 'Colombia', code: 'COL', iso: 'co' },
  { name: 'Mexico', code: 'MEX', iso: 'mx' },
  { name: 'United States', code: 'USA', iso: 'us', aliases: ['USA', 'United States of America'] },
  { name: 'Morocco', code: 'MAR', iso: 'ma' },
  { name: 'Japan', code: 'JPN', iso: 'jp' },
  { name: 'South Korea', code: 'KOR', iso: 'kr', aliases: ['Korea Republic', 'Republic of Korea'] },
  { name: 'Senegal', code: 'SEN', iso: 'sn' },
  { name: 'Switzerland', code: 'SUI', iso: 'ch' },
  { name: 'Denmark', code: 'DEN', iso: 'dk' },
  { name: 'Poland', code: 'POL', iso: 'pl' },
  { name: 'Serbia', code: 'SRB', iso: 'rs' },
  { name: 'Ghana', code: 'GHA', iso: 'gh' },
  { name: 'Cameroon', code: 'CMR', iso: 'cm' },
  { name: 'Ecuador', code: 'ECU', iso: 'ec' },
  { name: 'Australia', code: 'AUS', iso: 'au' },
  { name: 'Canada', code: 'CAN', iso: 'ca' },
  { name: 'Saudi Arabia', code: 'KSA', iso: 'sa' },
  { name: 'Qatar', code: 'QAT', iso: 'qa' },
  { name: 'Nigeria', code: 'NGA', iso: 'ng' },
  { name: 'Egypt', code: 'EGY', iso: 'eg' },
  { name: 'Ivory Coast', code: 'CIV', iso: 'ci', aliases: ["Cote d'Ivoire", 'Côte d’Ivoire'] },
  { name: 'Tunisia', code: 'TUN', iso: 'tn' },
  { name: 'Wales', code: 'WAL', iso: 'gb-wls' },
  { name: 'Scotland', code: 'SCO', iso: 'gb-sct' },
  { name: 'Austria', code: 'AUT', iso: 'at' },
  { name: 'Sweden', code: 'SWE', iso: 'se' },
  { name: 'Norway', code: 'NOR', iso: 'no' },
  { name: 'Turkey', code: 'TUR', iso: 'tr', aliases: ['Türkiye', 'Turkiye'] },
  { name: 'Ukraine', code: 'UKR', iso: 'ua' },
  { name: 'Peru', code: 'PER', iso: 'pe' },
  { name: 'Chile', code: 'CHI', iso: 'cl' },
  { name: 'Iran', code: 'IRN', iso: 'ir', aliases: ['IR Iran'] },
  { name: 'Costa Rica', code: 'CRC', iso: 'cr' },
  { name: 'Algeria', code: 'ALG', iso: 'dz' },
  { name: 'Paraguay', code: 'PAR', iso: 'py' },
  { name: 'Greece', code: 'GRE', iso: 'gr' },
];
